# _____       _           _                 
#|  __ \     (_)         | |                
#| |  | |_ __ _  ___  ___| |__   ___  _   _ 
#| |  | | '__| |/ _ \/ __| '_ \ / _ \| | | |
#| |__| | |  | |  __/\__ \ |_) | (_) | |_| |
#|_____/|_|  |_|\___||___/_.__/ \___/ \__, |
#                                      __/ |
#                                     |___/
CheckpointSaved: §bSaved
TeleportMessage: §6Teleporting to Checkpoint...
reward-command: givemoney {PLAYER} 50
EarnReward: You have finish the parkour
No-Checkpoint:
